comparisons numpy vs list

In [1]:
import numpy as np
import time
st = time.time()
py_list = [i*2 for i in range(100000000)]
end = time.time()
print(end-st)

st = time.time()
np_array = np.arange(100000000)*2
end = time.time()
print(end-st)

8.086886644363403
0.9626209735870361


numpy arrays

In [4]:
#1-d array
np_arr_1d = np.array([1,2,3,4,5])

#2-d array
np_arr_2d = np.array( [ [1,24,5] , [5,6,8] , [4,5,2]] )

#tensors
tesnsors = np.array( [[[1,4,2] , [2,6,5] , [5,7,2]] , [[10,0,2], [1,4,3], [2,1,3]]] )

print("\n=>", np_arr_1d, "\n\n\n=>", np_arr_2d, "\n\n\n=>", tesnsors)


=> [1 2 3 4 5] 


=> [[ 1 24  5]
 [ 5  6  8]
 [ 4  5  2]] 


=> [[[ 1  4  2]
  [ 2  6  5]
  [ 5  7  2]]

 [[10  0  2]
  [ 1  4  3]
  [ 2  1  3]]]


speacial matrixs

In [6]:
#zeros 
zeros = np.zeros((2,3));

#ones
ones = np.ones((3,5));

#const array
arr = np.full((4,6), 5);


print("\n=>", zeros, "\n\n\n=>", ones, "\n\n\n=>", arr)


=> [[0. 0. 0.]
 [0. 0. 0.]] 


=> [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 


=> [[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


random-arrays

In [ ]:
random_arr = np.random.random((2,4))*10

print("\n=>", random_arr)

random_arr2 = np.random.rand(2,4)*10

print("\n=>", random_arr2)

random_arr3 = np.random.randint(5, 50, (3,5)) #dim x,y , (shape)
print("\n=>", random_arr3)



=> [[1.7389988  4.04018137 6.34724687 7.69549201]
 [8.95706513 3.55340891 8.6925539  5.37679756]]

=> [[9.84787298 3.82832811 7.11639594 1.2887188 ]
 [0.82521513 0.2966655  1.35597956 7.70222518]]

=> [[ 6  7 41 30 43]
 [41 11 17 22 30]
 [16 22  9 32 18]]


sequences

In [11]:
seq = np.arange(20, 30, 2.5)
print("\n=>", seq)


=> [20.  22.5 25.  27.5]


Arrays propertices

In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape ", arr.shape) # (2,3)
print("Dimension ", arr.ndim) # row - 2
print("Size ", arr.size) # total ele = 2*3 = 6
print("DType ", arr.dtype) #dt - int


Shape  (2, 3)
Dimension  2
Size  6
DType  int64


Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array ", arr) # 0,1,2,3....,11

reshaped = arr.reshape((3, 4)) # convert into 3,4
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten() #make 2d to 1d
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel() #make 2d to 1d
print("\n raveled array ", raveled)

raveled[1] = 1e3 #chnage also orignal like refrence
print("\n raveled array2 ", raveled , " \nand original ", reshaped)


# Transpose
transpose = reshaped.T # make transponse :)
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array2  [   0 1000    2    3    4    5    6    7    8    9   10   11]  
and original  [[   0 1000    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]

 Transposed array  [[   0    4    8]
 [1000    5    9]
 [   2    6   10]
 [   3    7   11]]
